# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/ 

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: dev # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

local_backend: false

publish_mode: editorial_workflow

display_url: https://samanthazine.netlify.app

collections:
  - name: pages
    label: Pages
    delete: false
    files:
      - file: /pages/info.md
        label: Info
        name: info
        fields:
          - { label: layout, name: layout, widget: hidden, default: info }
          - {label: Text, name: text, required: false, widget: markdown,hint: "", default: "", buttons: ['link']}
          - {label: instagram, name: instagram, required: false, widget: string, hint: "", default: ""}
          - {label: image, name: image, required: false, widget: image}
      - file: /pages/shop.md
        label: Shop
        name: shop
        fields:
          - { label: layout, name: layout, widget: hidden, default: shop/shop-item }
          - {label: image, name: image, required: false, widget: image}
      - file: /pages/film.md
        label: Films
        name: film
        fields:
          - { label: layout, name: layout, widget: hidden, default: film/film }
          - {label: image, name: image, required: false, widget: image}
  - name: volume
    label: VOL.
    folder: _volume
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden,default: volume-layout, required: false }
      - { label: section, name: section, widget: hidden,default: volume, required: false }
      - {label: title, name: title, required: false, widget: string}
      - label: image
        name: image
        required: false
        widget: image
        media_library:
          config:
            multiple: true
  - name: Story
    label: STORY
    folder: _story
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden,default: story, required: false }
      - { label: section, name: section, widget: hidden,default: story, required: false }
      - {label: title, name: title, required: false, widget: string}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Art (quote + text)", "Fashion (only text - credits)", ""]
      - { label: Text, name: text, widget: 'markdown', required: false, hint: 'put credits or just text, you can add links.', buttons: ['link']}
      - {label: "Quote", name: "quote", widget: "text", hint: "put a quote", required: false}
      - {label: instagram link, name: instagram, required: false, widget: string}
      - label: Images
        name: images
        collapsed: true
        required: false
        widget: list
        allow_add: true
        field: {label: Image, name: image, widget: image}
      - label: Volume Relation
        name: volume
        required: false
        widget: relation
        collection: volume
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: title
  - name: film
    label: FILM
    folder: _film
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden,default: film-item-layout, required: false }
      - { label: section, name: section, widget: hidden,default: film, required: false }
      - {label: title, name: title, required: false, widget: string}
      - {label: Film URL, name: film-url,required: false,widget: string,hint: "put the google drive share URL(https://www.wonderplugin.com/online-tools/google-drive-direct-link-generator/), make sure it s not above 100mb. otherwise video won't show."}
      - { label: Text, name: text, widget: 'markdown', hint: 'about this film/credits', buttons: ['link']}
      - label: Image Placeholder
        name: image
        required: false
        widget: image
        media_library:
          config:
            multiple: true
      - label: Volume
        name: volume
        required: false
        widget: relation
        collection: volume
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: title
  - name: shop
    label: SHOP
    folder: _shop
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden,default: shop-item-layout, required: false }
      - {label: title, name: title, required: false, widget: string}
      - {label: "Description", name: "description", widget: "text", buttons: ['link']}
      - label: Price
        name: price
        required: false
        widget: number
        default: "0"
        valueType: int
        min: 0
        step: 1
      - label: Max Quantity
        name: max-quantity
        required: false
        widget: number
        hint: 'max quantity per customer'
        default: 1
        valueType: int
        min: 1
        step: 1
      - label: Ship this item?
        name: ship
        required: false
        widget: boolean
        hint: 'false will hide shipping info.'
        default: false
      - label: More Images
        name: images
        collapsed: true
        required: false
        widget: list
        allow_add: true
        field: {label: Image, name: image, widget: image}
