# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

display_url: https://samanathazine.netlify.app

collections:
  - name: pages
    label: Pages
    delete: false
    files:
      - file: /pages/info.md
        label: Info
        name: info
        fields:
          - label: layout
            name: layout
            widget: hidden
            default: info-layout
            required: true
            hint: ""
          - label: Text
            name: text
            required: true
            widget: markdown
            hint: ""
            default: ""
            buttons:
              - link
          - label: instagram
            name: instagram
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Over
            name: over
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Info Image
            name: info-image
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Shop Image
            name: shop-image
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Film Image
            name: Film Image
            required: true
            widget: string
            hint: ""
            default: ""
  - name: volume
    label: VOL.
    folder: _volume
    create: true
    slug: "{{slug}}"
    fields:
      - label: Layout
        name: layout
        required: true
        widget: hidden
        hint: ""
        default: volume-layout
      - label: title
        name: title
        required: true
        widget: string
        hint: vol. I
        default: ""
      - label: image
        name: image
        required: true
        widget: image
        hint: ""
        default: ""
        allow_multiple: false
    identifier_field: ""
  - name: Story
    label: STORY
    folder: _story
    create: true
    slug: "{{slug}}"
    fields:
      - label: Layout
        name: layout
        required: true
        widget: hidden
        hint: ""
        default: story-layout
      - label: Name
        name: name
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Instagram Link
        name: instagram
        required: false
        widget: string
        hint: ""
        default: ""
      - label: Images
        name: images
        required: true
        widget: list
        hint: ""
        default: ""
        allow_add: true
        field:
          label: Images
          name: image
          required: true
          widget: image
          hint: ""
          default: ""
          allow_multiple: false
        fields: ""
      - label: Volume Relation
        name: Volume
        required: true
        widget: relation
        hint: ""
        default: ""
        collection: volume
        displayFields: ["title"]
        searchFields: title
        valueField: title
        multiple: ""
        optionsLength: 20
      - label: Text
        name: Text
        required: false
        widget: markdown
        hint: put credits or just text, you can add links.
        default: ""
        buttons:
          - link
      - label: Quote
        name: quote
        required: false
        widget: text
        hint: put a quote
        default: ""
    identifier_field: ""
  - name: Film
    label: FILM
    folder: _film
    create: true
    slug: "{{slug}}"
    fields:
      - label: Layout
        name: layout
        required: true
        widget: hidden
        hint: ""
        default: film-item-layout
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Film URL
        name: film-url
        required: true
        widget: string
        hint: put the google drive share
          URL(https://www.wonderplugin.com/online-tools/google-drive-direct-link-generator/),
          make sure it s not above 100mb. otherwise video won't show.
        default: ""
      - label: Text
        name: text
        required: false
        widget: markdown
        hint: about this film
        default: ""
        buttons:
          - link
      - label: Volume
        name: volume
        required: true
        widget: relation
        hint: ""
        default: ""
        collection: volume
        displayFields: ["title"]
        searchFields: title
        valueField: title
        multiple: ""
        optionsLength: 20
    identifier_field: ""
  - name: shop
    label: SHOP
    folder: _shop
    create: true
    slug: "{{slug}}"
    fields:
      - label: Layout
        name: layout
        required: true
        widget: hidden
        hint: ""
        default: shop-item-layout
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Description
        name: description
        required: true
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - link
      - label: Price
        name: price
        required: true
        widget: number
        hint: ""
        default: "0"
        valueType: int
        min: "0"
        max: ""
        step: 1
      - label: Image
        name: image
        required: true
        widget: image
        hint: main image
        default: ""
        allow_multiple: false
      - label: Ship this item?
        name: ship
        required: false
        widget: boolean
        hint: false will hide shipping info.
        default: false
      - label: More Images
        name: images
        required: true
        widget: list
        hint: ""
        default: ""
        allow_add: true
        field:
          label: Image
          name: image
          required: false
          widget: image
          hint: ""
          default: ""
          allow_multiple: false
        fields: ""
      - label: Max Quantity
        name: max-quantity
        required: true
        widget: number
        hint: max quantity per customer
        default: "1"
        valueType: int
        min: "1"
        max: ""
        step: 1
    identifier_field: ""
