# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/ 

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: dev # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

local_backend: true

display_url: https://dev.samanthazine.com

publish_mode: editorial_workflow

editor:
    preview: false

collections:
  - name: shop
    label: Products
    folder: _shop
    create: true
    fields:
      - { label: text, name: text, widget: string }
      - { label: info, name: info, widget: string }
      - { label: id, name: product_id, widget: string }
      - {label: Image, name: image, widget: image }
  - name: pages
    label: Pages
    delete: false
    files:
      - file: /_data/settings.yml
        label: Settings
        name: Settings
        fields:
          - { label: text, name: text, widget: string }
          - {label: instagram, name: instagram, required: false, widget: string, hint: "", default: ""}
          - {label: donate link, name: donate, required: false, widget: string, hint: "", default: ""}
          - {label: email, name: email, required: false, widget: string, hint: "", default: ""}
  - name: volume
    label: VOL.
    folder: _volume
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden,default: volume-layout, required: false }
      - { label: section, name: section, widget: hidden,default: volume, required: false }
      - {label: title, name: title, required: false, widget: string}
      - label: image
        name: image
        required: false
        widget: image
        media_library:
          config:
            multiple: true
      - label: image back
        name: image-back
        required: false
        widget: image
        media_library:
          config:
            multiple: true
      - label: image spine
        name: image-spine
        required: false
        widget: image
        media_library:
          config:
            multiple: true
      - {label: text, name: text, required: false, widget: string}
      - { label: product id, name: product_id, required: false, widget: string }
      # - {label: price, name: price, required: false, widget: string}
      # - {label: pdf price difference, name: pdf-price, required: false, widget: string}
      - {label: Width (cm), name: width, required: false, widget: string}
      - {label: Height (cm), name: height, required: false, widget: string}
      - {label: page count, name: pagecount, required: false, widget: string}
  - name: Story
    label: STORY
    folder: _story
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden,default: story, required: false }
      - { label: section, name: section, widget: hidden,default: story, required: false }
      - {label: title, name: title, required: false, widget: string}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Art", "Fashion", ""]
      - { label: Text, name: text, widget: 'markdown', required: false, hint: 'just text', buttons: ['link']}
      - { label: Credits, name: credits, widget: 'markdown', required: false, hint: 'put credits, you can add links.', buttons: ['link']}
      - {label: "Quote", name: "quote", widget: "text", hint: "put a quote", required: false}
      - {label: instagram link, name: instagram, required: false, widget: string}
      - label: Images
        name: images
        collapsed: true
        required: false
        widget: list
        allow_add: true
        field: {label: Image, name: image, widget: image}
      - label: Volume Relation
        name: volume
        required: false
        widget: relation
        collection: volume
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: title
      - label: Film
        name: film
        required: false
        widget: relation
        collection: film
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: title
  - name: film
    label: FILM
    folder: _film
    create: true
    slug: "{{slug}}"
    fields:
      - { label: layout, name: layout, widget: hidden, default: film/film-item, required: false }
      - { label: section, name: section, widget: hidden,default: film, required: false }
      - {label: title, name: title, required: false, widget: string}
      - {label: Film URL, name: film-url,required: false,widget: string,hint: "put the google drive share URL(https://www.wonderplugin.com/online-tools/google-drive-direct-link-generator/), make sure it s not above 100mb. otherwise video won't show."}
      - { label: Text, name: text, widget: 'markdown', hint: 'about this film/credits', buttons: ['link']}
      - label: Image Placeholder
        name: image
        required: false
        widget: image
        media_library:
          config:
            multiple: true
      - label: Volume
        name: volume
        required: false
        widget: relation
        collection: volume
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: title
